services:
  app:
    image: bitnami/apache:2.4
    networks:
      - back-tier
    volumes:
      - ./source:/app
      - ./conf/vhost.conf:/vhosts/msc.conf:ro
    ports:
      - "80:8080"
      - "443:8443"
    depends_on:
      - php-fpm
      - bdd

  php-fpm:
    image: php_greg:latest
    networks:
      - back-tier
    volumes:
      - ./source:/var/www/html
      - ./php-custom:/etc/php81/php-fpm.d

  bdd:
    networks:
      - back-tier
    image: bitnami/mariadb:10.4
    env_file:
      - ./conf/env/mariadb.env
    ports:
      - "3308:3308"
    volumes:
        - db-data:/bitnami/mariadb
        - ./conf/dumps:/opt/bitnami/mysql/dumps

networks:
  back-tier:
    driver: bridge

volumes:
  db-data:

