version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
        - .env
    container_name: coralguardian-app
    ports:
        - '80:80'
    volumes:
        - .:/app
  mysql:
    image: mysql:latest
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=coralguardian
    container_name: coralguardian-db-mysql
    volumes:
        - .docker/persistent-data:/var/lib/mysql
    ports:
        - '3306:3306'
