version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    env_file:
        - .env
    container_name: coralguardian-app
    ports:
        - '80:80'
    volumes:
        - .:/app
    labels:
      - "traefik.http.routers.web.rule=Host(`www.coralguardian.org`)"

  mysql:
    image: yobasystems/alpine-mariadb
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=coralguardian
    container_name: coralguardian-db-mysql
    volumes:
        - mysql-storage:/var/lib/mysql
    ports:
        - '3306:3306'

volumes: 
  mysql-storage:
